import type { Metadata } from "next";
import { nominee, albertSans } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${albertSans.variable} ${nominee.variable} antialiased`}
        style={{ fontFamily: 'var(--font-albert-sans)' }}
      >
        {children}
      </body>
    </html>
  );
}
