'use client'
import { usePathname } from "next/navigation";
// import type { Metadata } from "next";
import { mainfont, albertSans } from "./fonts";
import "./globals.css";
import '@heroui/styles';
import { Providers } from "./providers";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollSmoother } from "gsap/ScrollSmoother";
import { ScrollTrigger } from "gsap/ScrollTrigger";

if (typeof window !== 'undefined') {
	gsap.registerPlugin(ScrollSmoother, ScrollTrigger);
}

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
	}: Readonly<{
		children: React.ReactNode;
	}>) {

	const pathname = usePathname();

	useGSAP(() => {
			ScrollSmoother.create({
				wrapper: "#smooth-wrapper",
				content: "#smooth-content",
				smooth: 2,
				effects: true,
				smoothTouch: 0.1,
				normalizeScroll: true,
			});
		},
		{
			dependencies: [pathname],
			revertOnUpdate: true,
		}
	)
	return (
		<html lang="en">
			<body
			className={`${albertSans.variable} ${mainfont.variable} antialiased`}
			// style={{ fontFamily: 'var(--font-albert-sans)' }}
			>
				<Providers>
					<div id="smooth-wrapper">
						<div id="smooth-content">
							{children}
						</div>
					</div>
				</Providers>
			</body>
		</html>
	);
}
